name: baby_1l_run_2
channels:
  - conda-forge
dependencies:
  - python
  - openmc>=0.14.0
  - openmc-plotter
  - numpy # add version tag
  - scipy # add version tag
  - matplotlib # add version tag
  - sympy
  - pandas
  - pint-pandas
  - nbconvert
  - ipykernel
  - pint
  - pip
  - pip:
      - git+https://github.com/libra-project/libra-toolbox@v0.3
      - openmc_data_downloader==0.6.0
      - matplotlib-label-lines
      - h-transport-materials~=0.17.0
